# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gcs_wid_telem_state.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget_telem_state(object):
    def setupUi(self, DockWidget_telem_state):
        DockWidget_telem_state.setObjectName("DockWidget_telem_state")
        DockWidget_telem_state.resize(238, 270)
        DockWidget_telem_state.setMaximumSize(QtCore.QSize(238, 270))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 161, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.line_4 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(0, 60, 231, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4_value.setGeometry(QtCore.QRect(190, 100, 31, 20))
        self.label_4_value.setText("")
        self.label_4_value.setObjectName("label_4_value")
        self.line_6 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_6.setGeometry(QtCore.QRect(220, 10, 20, 241))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 161, 20))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.line_7 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_7.setGeometry(QtCore.QRect(0, 120, 231, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_5 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 231, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_1 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(0, 30, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(170, 10, 20, 241))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 231, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3_value.setGeometry(QtCore.QRect(190, 70, 31, 20))
        self.label_3_value.setText("")
        self.label_3_value.setObjectName("label_3_value")
        self.label_2_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2_value.setGeometry(QtCore.QRect(190, 40, 31, 20))
        self.label_2_value.setText("")
        self.label_2_value.setObjectName("label_2_value")
        self.label_1_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_1_value.setGeometry(QtCore.QRect(190, 10, 31, 20))
        self.label_1_value.setText("")
        self.label_1_value.setObjectName("label_1_value")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 161, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 161, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.line_8 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_8.setGeometry(QtCore.QRect(0, 150, 231, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_9.setGeometry(QtCore.QRect(0, 180, 231, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_10.setGeometry(QtCore.QRect(0, 210, 231, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 161, 20))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 161, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.line_11 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_11.setGeometry(QtCore.QRect(0, 240, 231, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_5_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5_value.setGeometry(QtCore.QRect(190, 130, 31, 20))
        self.label_5_value.setText("")
        self.label_5_value.setObjectName("label_5_value")
        self.label_6_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6_value.setGeometry(QtCore.QRect(190, 160, 31, 20))
        self.label_6_value.setText("")
        self.label_6_value.setObjectName("label_6_value")
        self.label_7_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7_value.setGeometry(QtCore.QRect(190, 190, 31, 20))
        self.label_7_value.setText("")
        self.label_7_value.setObjectName("label_7_value")
        self.label_8_value = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8_value.setGeometry(QtCore.QRect(190, 220, 31, 20))
        self.label_8_value.setText("")
        self.label_8_value.setObjectName("label_8_value")
        DockWidget_telem_state.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_telem_state)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_telem_state)

    def retranslateUi(self, DockWidget_telem_state):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_telem_state.setWindowTitle(_translate("DockWidget_telem_state", "DockWidget"))

